SELECT PR.ID, MOVIES.NAME, PR.TYPE, PR.DATE, PR.TIME, 100- COUNT(RS.ID)
    FROM MOVIES
    LEFT JOIN PROJECTIONS AS PR ON MOVIES.ID == PR.MOVIE_ID
    LEFT JOIN RESERVATIONS AS RS ON RS.PROJECTION_ID == PR.ID
    GROUP BY PROJECTION_ID, MOVIES.ID
    HAVING MOVIES.ID == 5
    ORDER BY DATE;