DROP_PATIENT_TABLE = '''
    DROP TABLE IF EXISTS PATIENT
'''

DROP_DOCTOR_TABLE = '''
    DROP TABLE IF EXISTS DOCTOR
'''

DROP_HOSPITAL_STAY_TABLE = '''
    DROP TABLE IF EXISTS HOSPITAL_STAY
'''

CREATE_DOCTOR_TABLE = '''
    CREATE TABLE IF NOT EXISTS DOCTOR (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        FIRSTNAME TEXT NOT NULL,
        LASTNAME TEXT NOT NULL,
        ACADEMIC_TITLE TEXT
    )
'''

CREATE_PATIENT_TABLE = '''
    CREATE TABLE IF NOT EXISTS PATIENT (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        FIRSTNAME TEXT NOT NULL,
        LASTNAME TEXT NOT NULL,
        AGE INTEGER NOT NULL,
        GENDER CHAR(1) NOT NULL,
        DOCTOR_ID INTEGER,
        FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(ID)
    )
'''

CREATE_HOSPITAL_STAY_TABLE = '''
    CREATE TABLE IF NOT EXISTS HOSPITAL_STAY (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        STARTDATE TEXT NOT NULL,
        ENDDATE TEXT,
        ROOM INTEGER NOT NULL,
        INJURY TEXT NOT NULL,
        PATIENT_ID INTEGER,
        FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(ID)
    )
'''

LIST_PATIENT_IDS = ''' SELECT ID FROM PATIENT '''

LIST_DOCTOR_IDS = ''' SELECT ID FROM DOCTOR '''

LIST_HOSPITAL_STAY_IDS = ''' SELECT ID FROM HOSPITAL_STAY '''

ADD_PATIENT = '''
    INSERT INTO PATIENT(FIRSTNAME, LASTNAME, AGE, GENDER, DOCTOR_ID)
    VALUES(?, ?, ?, ?, ?)
'''

ADD_DOCTOR = '''
    INSERT INTO DOCTOR(FIRSTNAME, LASTNAME, ACADEMIC_TITLE)
    VALUES(?, ?, ?)
'''

ADD_HOSPITAL_STAY = '''
    INSERT INTO HOSPITAL_STAY(STARTDATE, ENDDATE, ROOM, INJURY, PATIENT_ID)
    VALUES(?, ?, ?, ?, ?)
'''

DELETE_PATIENT = '''
    DELETE FROM PATIENT WHERE ID=?
'''

DELETE_DOCTOR = '''
    DELETE FROM DOCTOR WHERE ID=?
'''

DELETE_HOSPITAL_STAY = '''
    DELETE FROM HOSPITAL_STAY WHERE ID=?
'''

LIST_ALL_PATIENTS = '''
    SELECT ID, FIRSTNAME, LASTNAME, AGE
    FROM PATIENT
'''

LIST_ALL_DOCTORS = '''
    SELECT ID, FIRSTNAME, LASTNAME, ACADEMIC_TITLE
    FROM DOCTOR
'''

UPDATE_PATIENT_FIRSTNAME = '''
    UPDATE PATIENT
    SET FIRSTNAME=?
    WHERE ID=?
'''

UPDATE_PATIENT_LASTNAME = '''
    UPDATE PATIENT
    SET LASTNAME=?
    WHERE ID=?
'''
UPDATE_PATIENT_AGE = '''
    UPDATE PATIENT
    SET AGE=?
    WHERE ID=?
'''

UPDATE_PATIENT_DOCTOR_ID = '''
    UPDATE PATIENT
    SET DOCTOR_ID=?
    WHERE ID=?
'''

UPDATE_DOCTOR_FIRSTNAME = '''
    UPDATE DOCTOR
    SET FIRSTNAME=?
    WHERE ID=?
'''

UPDATE_DOCTOR_LASTNAME = '''
    UPDATE DOCTOR
    SET LASTNAME=?
    WHERE ID=?
'''

UPDATE_DOCTOR_ACADEMIC_TITLE = '''
    UPDATE DOCTOR
    SET ACADEMIC_TITLE=?
    WHERE ID=?
'''

UPDATE_HS_STARTDATE = '''
    UPDATE HOSPITAL_STAY
    SET STARTDATE=?
    WHERE ID=?
'''

UPDATE_HS_ENDTDATE = '''
    UPDATE HOSPITAL_STAY
    SET ENDDATE=?
    WHERE ID=?
'''

UPDATE_HS_ROOM = '''
    UPDATE HOSPITAL_STAY
    SET ROOM=?
    WHERE ID=?
'''

UPDATE_HS_INJURY = '''
    UPDATE HOSPITAL_STAY
    SET INJURY=?
    WHERE ID=?
'''

UPDATE_HS_PATIENT_ID = '''
    UPDATE HOSPITAL_STAY
    SET PATIENT_ID=?
    WHERE ID=?
'''

LIST_PATIENTS_OF_DOCTOR = '''
    SELECT PATIENT.ID, PATIENT.FIRSTNAME, PATIENT.LASTNAME, PATIENT.AGE
    FROM DOCTOR
    LEFT JOIN PATIENT ON DOCTOR.ID = PATIENT.DOCTOR_ID
    WHERE DOCTOR.ID=?
'''

PATIENTS_GROUP_BY_INJURY = '''
    SELECT PATIENT.ID, PATIENT.FIRSTNAME, PATIENT.LASTNAME, PATIENT.AGE
    FROM HOSPITAL_STAY
    LEFT JOIN PATIENT ON PATIENT.ID = HOSPITAL_STAY.PATIENT_ID
    WHERE HOSPITAL_STAY.INJURY=?
'''

DOCTORS_DISIESES = '''
    SELECT DOCTOR.FIRSTNAME||' '||DOCTOR.LASTNAME,
            GROUP_CONCAT(DISTINCT HOSPITAL_STAY.INJURY)
    FROM DOCTOR
    LEFT JOIN PATIENT ON DOCTOR.ID = PATIENT.DOCTOR_ID
    LEFT JOIN HOSPITAL_STAY ON PATIENT.ID = HOSPITAL_STAY.PATIENT_ID
    GROUP BY DOCTOR.ID
'''

PATIENTS_BETWEEN_DATES = '''
    SELECT PATIENT.ID, PATIENT.FIRSTNAME, PATIENT.LASTNAME, PATIENT.AGE
    FROM PATIENT
    JOIN HOSPITAL_STAY AS HS ON PATIENT.ID = HS.PATIENT_ID
    WHERE HS.STARTDATE > DATETIME(?) AND HS.ENDDATE < DATETIME(?)
'''
